[workspace]
resolver = "2"
members = [
    "crates/gram-indexer",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["GramBondhon Core Team <engineering@grambondhon.bd>"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
tokio = { version = "1.38", features = ["full"] }
alloy = { version = "0.1.1", features = ["full"] }
sqlx = { version = "0.8", default-features = false, features = [
    "runtime-tokio-rustls",
    "postgres",
    "macros",
    "chrono",
    "json",
    "uuid",
] }
redis = { version = "0.26", features = ["tokio-comp", "aio"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
dotenvy = "0.15"
thiserror = "1.0"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.8", features = ["v4", "serde"] }
futures-util = "0.3"
